import { withAutoAnimate } from "./animated-icon";

import ArrowBackIconRaw from "./arrow-back-icon";
import ArrowNarrowRightIconRaw from "./arrow-narrow-right-icon";
import BookIconRaw from "./book-icon";
import BrainCircuitIconRaw from "./brain-circuit-icon";
import BrightnessDownIconRaw from "./brightness-down-icon";
import BugIconRaw from "./bug-icon";
import CheckedIconRaw from "./checked-icon";
import CodeIconRaw from "./code-icon";
import CodeXmlIconRaw from "./code-xml-icon";
import ClockIconRaw from "./clock-icon";
import DownChevronIconRaw from "./down-chevron";
import FileDescriptionIconRaw from "./file-description-icon";
import GearIconRaw from "./gear-icon";
import GlobeIconRaw from "./globe-icon";
import HistoryCircleIconRaw from "./history-circle-icon";
import HomeIconRaw from "./home-icon";
import LayoutDashboardIconRaw from "./layout-dashboard-icon";
import LayoutSidebarRightIconRaw from "./layout-sidebar-right-icon";
import LayersIconRaw from "./layers-icon";
import LibraryIconRaw from "./library-icon";
import LogoutIconRaw from "./logout-icon";
import MagnifierIconRaw from "./magnifier-icon";
import MoonIconRaw from "./moon-icon";
import PlusIconRaw from "./plus-icon";
import RefreshIconRaw from "./refresh-icon";
import RightChevronIconRaw from "./right-chevron";
import SendIconRaw from "./send-icon";
import ShieldCheckIconRaw from "./shield-check";
import SparklesIconRaw from "./sparkles-icon";
import TrashIconRaw from "./trash-icon";
import XIconRaw from "./x-icon";

export const ArrowBackIcon = withAutoAnimate(ArrowBackIconRaw);
export const ArrowNarrowRightIcon = withAutoAnimate(ArrowNarrowRightIconRaw);
export const BookIcon = withAutoAnimate(BookIconRaw);
export const BrainCircuitIcon = withAutoAnimate(BrainCircuitIconRaw);
export const BrightnessDownIcon = withAutoAnimate(BrightnessDownIconRaw);
export const BugIcon = withAutoAnimate(BugIconRaw);
export const CheckedIcon = withAutoAnimate(CheckedIconRaw);
export const CodeIcon = withAutoAnimate(CodeIconRaw);
export const CodeXmlIcon = withAutoAnimate(CodeXmlIconRaw);
export const ClockIcon = withAutoAnimate(ClockIconRaw);
export const DownChevronIcon = withAutoAnimate(DownChevronIconRaw);
export const FileDescriptionIcon = withAutoAnimate(FileDescriptionIconRaw);
export const GearIcon = withAutoAnimate(GearIconRaw);
export const GlobeIcon = withAutoAnimate(GlobeIconRaw);
export const HistoryCircleIcon = withAutoAnimate(HistoryCircleIconRaw);
export const HomeIcon = withAutoAnimate(HomeIconRaw);
export const LayoutDashboardIcon = withAutoAnimate(LayoutDashboardIconRaw);
export const LayoutSidebarRightIcon = withAutoAnimate(LayoutSidebarRightIconRaw);
export const LayersIcon = withAutoAnimate(LayersIconRaw);
export const LibraryIcon = withAutoAnimate(LibraryIconRaw);
export const LogoutIcon = withAutoAnimate(LogoutIconRaw);
export const MagnifierIcon = withAutoAnimate(MagnifierIconRaw);
export const MoonIcon = withAutoAnimate(MoonIconRaw);
export const PlusIcon = withAutoAnimate(PlusIconRaw);
export const RefreshIcon = withAutoAnimate(RefreshIconRaw);
export const RightChevronIcon = withAutoAnimate(RightChevronIconRaw);
export const SendIcon = withAutoAnimate(SendIconRaw);
export const ShieldCheckIcon = withAutoAnimate(ShieldCheckIconRaw);
export const SparklesIcon = withAutoAnimate(SparklesIconRaw);
export const TrashIcon = withAutoAnimate(TrashIconRaw);
export const XIcon = withAutoAnimate(XIconRaw);

export type { AnimatedIconProps, AnimatedIconHandle } from "./types";
