/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeSymbol {
  name: string;
  symbolType: string;
  exported: boolean;
  startLine: number;
  endLine: number;
  receiver?: string;
}
export interface NativeCallExpression {
  callerName: string;
  calleeName: string;
}
export interface NativeParseResult {
  symbols: Array<NativeSymbol>;
  importPaths: Array<string>;
  calledIdentifiers: Array<string>;
  callExpressions: Array<NativeCallExpression>;
}
export interface NativeChunk {
  content: string;
  startLine: number;
  endLine: number;
}
export interface NativeParseAndChunkResult {
  symbols: Array<NativeSymbol>;
  importPaths: Array<string>;
  calledIdentifiers: Array<string>;
  callExpressions: Array<NativeCallExpression>;
  chunks: Array<NativeChunk>;
}
export interface ParseBatchItem {
  language: string;
  content: string;
}
export declare function parseCodeNative(
  language: string,
  content: string,
): NativeParseResult | null;
/**
 * Batch parse — parses all files in parallel using rayon.
 * Returns results in the same order as input. null entries = parse failed/empty.
 */
export declare function parseCodeBatch(
  items: Array<ParseBatchItem>,
): Array<NativeParseResult | undefined | null>;
/**
 * Batch parse + chunk — parses all files in parallel and creates 80-line chunks.
 * Returns results in the same order as input. null entries = parse failed/empty.
 * During indexing, only chunks are needed — symbols/calls are extracted lazily during graph build.
 */
export declare function parseAndChunkBatch(
  items: Array<ParseBatchItem>,
): Array<NativeParseAndChunkResult | undefined | null>;
export interface ScannedFile {
  absolutePath: string;
  relativePath: string;
  sizeBytes: number;
  mtimeMs: number;
}
export declare function scanWorkspaceFast(
  rootPath: string,
  allowedExtensions: Array<string>,
): Array<ScannedFile>;
export interface NativeChunk {
  content: string;
  tokenCount: number;
  contentHash: string;
  heading?: string;
}
/**
 * Returns indices into the original chunk list for each output chunk.
 * Each entry: (original_index, split_index, split_count) or (-1, 0, 0) for a merged chunk.
 * For merged chunks, the first original index is the start of the merge group.
 */
export interface BoundPlan {
  content: string;
  tokenCount: number;
  contentHash: string;
  heading?: string;
  sourceIndex: number;
  splitIndex: number;
  splitCount: number;
  mergedIndices: Array<number>;
}
export declare function boundChunks(
  chunks: Array<NativeChunk>,
  targetTokens: number,
  overlapTokens: number,
): Array<BoundPlan>;
