/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScannedFile {
  absolutePath: string;
  relativePath: string;
  sizeBytes: number;
  mtimeMs: number;
}
export declare function scanWorkspaceFast(
  rootPath: string,
  allowedExtensions: Array<string>,
): Array<ScannedFile>;
export declare function fastHash(content: string): string;
export declare function fastHashBytes(bytes: Uint8Array): string;
export interface NativeChunk {
  content: string;
  tokenCount: number;
  contentHash: string;
  heading?: string;
}
/**
 * Returns indices into the original chunk list for each output chunk.
 * Each entry: (original_index, split_index, split_count) or (-1, 0, 0) for a merged chunk.
 * For merged chunks, the first original index is the start of the merge group.
 */
export interface BoundPlan {
  content: string;
  tokenCount: number;
  contentHash: string;
  heading?: string;
  sourceIndex: number;
  splitIndex: number;
  splitCount: number;
  mergedIndices: Array<number>;
}
export declare function boundChunks(
  chunks: Array<NativeChunk>,
  targetTokens: number,
  overlapTokens: number,
): Array<BoundPlan>;
